[profile.default]
libs = ["lib"]
out = "out"
remappings = [
  "@layerzerolabs/=lib/solidity-examples/contracts/",
  "solidity-examples/=lib/solidity-examples/contracts/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
src = "src"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
